# Generated by Django 4.2.8 on 2023-12-19 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtickets',
            name='sold_date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
    ]
